title: LabelStudio-MIR Docs
description: LabelStudio interfaces for music information retrieval tasks!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
